version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli-uglify
    versions:
    - "> 2.1.0"
  - dependency-name: ember-cli
    versions:
    - 3.23.0
    - 3.24.0
  - dependency-name: ember-source
    versions:
    - 3.24.0
    - 3.24.1
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: ember-cli-htmlbars-inline-precompile
    versions:
    - 3.0.1
